name: Publish Python Package to PyPI

on:
  release:
    types: [created]
  workflow_run:
    workflows: ["Bump Version"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'release' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')) && github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: ${{ github.event.release.tag_name || 'main' }}
    
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv twine toml
    
    - name: Build package
      run: |
        rm -rf dist/
        uv build --no-sources
        
    - name: Check distribution with twine
      run: |
        twine check dist/*
        
    - name: Publish to PyPI
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
        
    - name: Extract package version
      id: get_version
      run: |
        PACKAGE_VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])")
        echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
    
    - name: Notify Slack about PyPI release
      id: slack
      uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: |
          :rocket: *New Release Published to PyPI!*
          
          *Package:* codelogic-mcp-server v${{ steps.get_version.outputs.version }}
          *Published by:* ${{ github.actor }}
          
          :link: <https://pypi.org/project/codelogic-mcp-server/${{ steps.get_version.outputs.version }}|View on PyPI>
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}